### ISSUE TITLE
Display blank page at load

### ISSUE THREAD

**Issue by yann300** [EdsonAlcala/remix-gas-profiler#1]
When the plugin load, a blank page is shown.
It should perhaps display a link to this repository with some explanation on how it works.
Note that remix-plugin inject bootstrap css. 
So you can use things like:
https://getbootstrap.com/docs/4.3/components/alerts/

**Comment by yann300** [comment]
Associated with link, author mail and issue page should be displayed.
Also if you provide a link to doc, we can display it directly in remix IDE

**Comment by EdsonAlcala** [comment]
what about something like this?
![Screen Shot 2019-08-15 at 17 35 32](https://user-images.githubusercontent.com/3077635/63110357-242c1300-bf83-11e9-8e44-9f5d4f2dea6a.png)

**Comment by yann300** [comment]
With the link to github and some bootstrap css like https://getbootstrap.com/docs/4.3/components/card/#body
that sounds good ;)

**Comment by EdsonAlcala** [comment]
yes, I'll apply styling

**Comment by EdsonAlcala** [comment]
Fixed in https://github.com/EdsonAlcala/remix-gas-profiler/pull/6
