### ISSUE TITLE
When profiling is shown the transaction hash should be displayed

### ISSUE THREAD

**Issue by yann300** [EdsonAlcala/remix-gas-profiler#2]
with if available some information about the transaction.

**Comment by EdsonAlcala** [comment]
The transaction has the following fields:
![Screen Shot 2019-08-15 at 17 46 38](https://user-images.githubusercontent.com/3077635/63111030-acf77e80-bf84-11e9-8b15-e3727f50cb85.png)

Maybe transactionCosts and executionCosts?

Do you think the hash is also important? or any other field?

**Comment by yann300** [comment]
any field that can identify the context is important. So `contractAddress` and `hash` i 'd say

**Comment by EdsonAlcala** [comment]
fixed in https://github.com/EdsonAlcala/remix-gas-profiler/pull/6
