### ISSUE TITLE
Would be handy to update the plugin status

### ISSUE THREAD

**Issue by yann300** [EdsonAlcala/remix-gas-profiler#3]
using https://github.com/ethereum/remix-plugin#status
when a new profiling is done and available

**Comment by EdsonAlcala** [comment]
It means after each transaction and once the profiling has been generated I need to do a call to

client.emit('statusChanged', { key: 'succeed', type: 'success', title: 'New profiling ready !' })

?

**Comment by yann300** [comment]
yes and perhaps the `title` should contain the transaction hash (that will add the status in the vertical icons).

**Comment by EdsonAlcala** [comment]
fixed in https://github.com/EdsonAlcala/remix-gas-profiler/pull/6
